name: Deploy site
on:
  push:
    branches:
      - refresh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public/
          clean-exclude: pr-preview/
          github-token: ${{ secrets.ACCESS_TOKEN }}
